'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CoEasy_Database
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CoEasy_Database")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tblCoworker() As DbSet(Of Coworker)
    Public Overridable Property tblEinkauf() As DbSet(Of Einkauf)
    Public Overridable Property tblEinkaufsposition() As DbSet(Of Einkaufsposition)
    Public Overridable Property tblMitarbeiter() As DbSet(Of Mitarbeiter)
    Public Overridable Property tblTicket() As DbSet(Of Ticket)
    Public Overridable Property tblWLAN() As DbSet(Of WLAN)

End Class
