'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CoworkerEntity
    Public Property CoworkerIdPk As Integer
    Public Property Benutzername As String
    Public Property Passwort As String
    Public Property Vorname As String
    Public Property Name As String
    Public Property Email As String
    Public Property Adresse As String
    Public Property Steuernummer As String
    Public Property Firmenname As String
    Public Property EinkaufIdFk As Nullable(Of Integer)

    Public Overridable Property tblEinkauf As EinkaufEntity

End Class
