'------------------------------------------------------------------------------
' <auto-generated>
'     Der Code wurde von einer Vorlage generiert.
'
'     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
'     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EinkaufspositionEntity
    Public Property EinkaufspositionIdPk As Integer
    Public Property Anzahl As Integer
    Public Property Totalpreis As Decimal
    Public Property TicketIdFk As Integer
    Public Property WlanIdFk As Integer
    Public Property EinkaufIdFk As Integer

    Public Overridable Property tblEinkauf As EinkaufEntity
    Public Overridable Property tblTicket As TicketEntity
    Public Overridable Property tblWLAN As WLANEntity

End Class
